### ISSUE TITLE
Mapnik docker doesn't build... again

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles-tools#359]
All pull requests fail again due to Mapnik not compiling as part of the generate-tiles:

```

Step 4/8 : RUN npm install -g           mapnik@3.7.2           @mapbox/mbtiles@0.11.0           @mapbox/tilelive@6.1.0           tilelive-tmsource@0.8.2           --unsafe-perm
 ---> Running in 329f7e2fdc86
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated queue-async@1.0.7: renamed to d3-queue
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason
/usr/local/bin/tilelive-copy -> /usr/local/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy
/usr/local/bin/mapnik-index.js -> /usr/local/lib/node_modules/mapnik/bin/mapnik-index.js
/usr/local/bin/mapnik-inspect.js -> /usr/local/lib/node_modules/mapnik/bin/mapnik-inspect.js
/usr/local/bin/mapnik-render.js -> /usr/local/lib/node_modules/mapnik/bin/mapnik-render.js
/usr/local/bin/mapnik-shapeindex.js -> /usr/local/lib/node_modules/mapnik/bin/mapnik-shapeindex.js

> sqlite3@4.2.0 install /usr/local/lib/node_modules/@mapbox/mbtiles/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: Cannot read property 'apply' of undefined
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@mapbox/mbtiles/node_modules/needle/lib/needle.js:618:21)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:315:30)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:552:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:454:20)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:263:12)
node-pre-gyp ERR! System Linux 5.8.0-1039-azure
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@mapbox/mbtiles/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/@mapbox/mbtiles/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-25T00_33_23_189Z-debug.log
The command '/bin/sh -c npm install -g           mapnik@3.7.2           @mapbox/mbtiles@0.11.0           @mapbox/tilelive@6.1.0           tilelive-tmsource@0.8.2           --unsafe-perm' returned a non-zero code: 7

Error: Process completed with exit code 7.
```

cc: @zstadler @kukulich

**Comment by TomPohys** [comment]
Build docker `generate-vectortiles` is functional. Tested by local build and also CI build was finished (https://github.com/openmaptiles/openmaptiles-tools/runs/4051532924?check_suite_focus=true#step:3:11391)
