### ISSUE TITLE
testOnStartup default tile Tile does not exist error

### ISSUE THREAD

**Issue by lazaa32** [openmaptiles/openmaptiles-tools#382]
PR #381 solved the issue with generating tiles over zoom 14 by adding `&minzoom=${MIN_ZOOM}&maxzoom=${MAX_ZOOM}` to `$PGQUERY` string. However, if `MAX_ZOOM`<14 (e.g. default `MAX_ZOOM=7` in `.env`), a user gets an error:

```
Verifying pgquery data source by retrieving a tile at [14,9268,3575] from postgres:5432/openmaptiles...
Failed to get a tile at [14,9268,3575] from postgres:5432/openmaptiles (in 0ms), aborting tilelive-pgquery initialization:
Error: Tile does not exist
/usr/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

Error: Tile does not exist
    at PgQuery._getRawTileAsync (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:272:13)
    at PgQuery._testSingleServer (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:420:60)
    at /usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:478:66
    at Array.map (<anonymous>)
    at PgQuery.testOnStartupAsync (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:478:52)
    at PgQuery.init (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:117:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR: 1
make: *** [Makefile:458: generate-tiles-pg] Error 1
```

It is because PgQuery tries to generate test tile (14/9268/3575) which is out of bounds `MIN_ZOOM`-`MAX_ZOOM` (e.g. 0-7).
You can use `testOnStartup` parameter and define tile in bounds of `MIN_ZOOM`-`MAX_ZOOM` which fixes this problem but it doesn't look very user-friendly to force user to set this parameter.

@nyurik what do you think? First, I thought we could change the default test tile (e.g. to a tile at zoom 7 as that's default `MAX_ZOOM` in `.env`) but now that seems to me like a solution that is not generic enough.

Full log
```
make generate-tiles-pg area=andorra
Starting postgres docker compose target using default image (no recreate if exists)
Wait for PostgreSQL to start...
docker-compose run --rm --user=1001:1001 openmaptiles-tools pgwait
Creating planet_openmaptiles-tools_run ... done
Generating tiles into data/tiles.mbtiles (will delete if already exists)...
docker-compose run --rm --user=1001:1001 openmaptiles-tools generate-tiles
Creating planet_openmaptiles-tools_run ... done
pgquery://?database=openmaptiles&host=postgres&port=5432&username=openmaptiles&password=openmaptiles&funcZXY=getmvt&maxpool=10&key=1&minzoom=0&maxzoom=7
Generating zoom 0..7 from 1 servers, using 10 connections per server, 10 parallel streams...
tilelive-pgquery v1.1.0
Tilejson Spec:
       tilejson = 2.1.0
           name = PgQuery 1.1.0
         format = pbf
             id = openmaptiles
    attribution = <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>
         bounds = -180,-85.0511,180,85.0511
         center = -12.2168,28.6135,4
        minzoom = 0
        maxzoom = 7
    pixel_scale = 256
      maskLevel = 8
        version = 3.9

Server information for postgres:5432:
                         version() = PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
            postgis_full_version() = POSTGIS="3.1.4 ded6c34" [EXTENSION] PGSQL="130" GEOS="3.9.0-CAPI-1.16.2" PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.5.0 (Internal)" (core procs from "3.1.2 cbe925d" need upgrade)
                               jit = off
                    shared_buffers = 16GB
                          work_mem = 10485kB
              maintenance_work_mem = 2GB
              effective_cache_size = 48GB
          effective_io_concurrency = 200
                   max_connections = 200
              max_worker_processes = 32
              max_parallel_workers = 8
   max_parallel_workers_per_gather = 0
                       wal_buffers = 16MB
                      min_wal_size = 4GB
                      max_wal_size = 16GB
                  random_page_cost = 1.1
         default_statistics_target = 500
      checkpoint_completion_target = 0.9

Verifying pgquery data source by retrieving a tile at [14,9268,3575] from postgres:5432/openmaptiles...
Failed to get a tile at [14,9268,3575] from postgres:5432/openmaptiles (in 0ms), aborting tilelive-pgquery initialization:
Error: Tile does not exist
/usr/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

Error: Tile does not exist
    at PgQuery._getRawTileAsync (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:272:13)
    at PgQuery._testSingleServer (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:420:60)
    at /usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:478:66
    at Array.map (<anonymous>)
    at PgQuery.testOnStartupAsync (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:478:52)
    at PgQuery.init (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:117:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR: 1
make: *** [Makefile:458: generate-tiles-pg] Error 1
```

**Comment by TomPohys** [comment]
Implemented in tilelive-pgquery:1.2.0 (https://github.com/openmaptiles/openmaptiles-tools/blob/2b94a8fa869a868d64b3559435db5f5929f4d6f6/Dockerfile#L127)
