### ISSUE TITLE
copy failed between 2 mbtiles generated with quickstart.sh

### ISSUE THREAD

**Issue by guillaumerose** [openmaptiles/openmaptiles-tools#395]
I am trying to merge 2 regions mbtiles into one. I generated them with ./quickstart.sh and run this command:

```
$ mbtiles-tools copy src.mbtiles dst.mbtiles
Opening target.mbtiles
Traceback (most recent call last):
  File "/usr/src/app/mbtiles-tools", line 188, in <module>
    main()
  File "/usr/src/app/mbtiles-tools", line 120, in main
    TileCopier(source=Metadata(args['<mbtiles-file>'], args['--show-json'],
  File "/usr/src/app/openmaptiles/mbtile_tools.py", line 467, in run
    self.copy_tiles(cursor)
  File "/usr/src/app/openmaptiles/mbtile_tools.py", line 473, in copy_tiles
    self.execute(cursor, sql, params)
  File "/usr/src/app/openmaptiles/mbtile_tools.py", line 549, in execute
    cursor.execute(sql, params if params else [])
sqlite3.OperationalError: table map has 5 columns but 4 values were supplied
```

src and dst are the 2 files generated by quickstart. I think it should work.

**Comment by guillaumerose** [comment]
Workaround by using a temporary mbtiles: 

Copy src to tmp.mbtiles
Copy dst to tmp.mbtiles
Replace dst by tmp.
