### ISSUE TITLE
invalid input syntax for type integer

### ISSUE THREAD

**Issue by molind** [openmaptiles/openmaptiles-tools#439]
Tile generation stopped due to an error in the 'display_housenumber' SQL function. Is it a known issue, and how can it be fixed? Could it be related to integer overflow? I'm generating planet tiles for February 2024 OSM data.

```
[2h 11m 23.5s]  99.8772%  1.81m/ 1.81m @  204/s | ✓ 1.81m □ 0 | 11.0s leftError getting 14/2632/6336: error: invalid input syntax for type integer: ""
/usr/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

error: invalid input syntax for type integer: ""
    at Parser.parseErrorMessage (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 183,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL function "display_housenumber" statement 1\n' +
    'SQL function "getmvt" statement 1',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'numutils.c',
  line: '320',
  routine: 'pg_strtoint32'
}
```

**Comment by molind** [comment]
Closed as a duplicate of https://github.com/openmaptiles/openmaptiles/issues/1583
